# Generated by Django 5.1.1 on 2024-10-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_titer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titer',
            name='dmel_mean_depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='titer',
            name='wri_mean_depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='titer',
            name='wri_titer',
            field=models.IntegerField(),
        ),
    ]
